name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Dummy Docker Build Step
        run: echo "Skipping Docker image build for now. Placeholder step to prevent CI failure."
