const MORRO_API_BASE_URL = process.env.EXPO_PUBLIC_MORRO_API_BASE_URL || '';
const MAPBOX_ACCESS_TOKEN = process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN || '';
const MQTT_BROKER_URL = process.env.EXPO_PUBLIC_MQTT_BROKER_URL || '';
const MQTT_PORT = process.env.EXPO_PUBLIC_MQTT_PORT || '';
const MQTT_TOPIC_RIDE_REQUESTS =
  process.env.EXPO_PUBLIC_MQTT_TOPIC_RIDE_REQUESTS_BASE || '';
const MQTT_TOPIC_DRIVER_LOCATION =
  process.env.EXPO_PUBLIC_MQTT_TOPIC_DRIVER_LOCATION_BASE || '';

console.log(
  `MQTT_TOPIC_DRIVER_LOCATION: `,
  MQTT_TOPIC_DRIVER_LOCATION
);

export default {
  MORRO_API_BASE_URL,
  MAPBOX_ACCESS_TOKEN,
  MQTT_BROKER_URL,
  MQTT_PORT,
  MQTT_TOPIC_RIDE_REQUESTS,
  MQTT_TOPIC_DRIVER_LOCATION
};
